### ISSUE TITLE
A ver las banderas

### ISSUE THREAD

**Issue by gmagannaDevelop** [edwinb-ai/edwinb-ai#1]
:fr: :it: :es: :gb: :honduras:

**Comment by gmagannaDevelop** [comment]
Ah prro sí jalan

**Comment by gmagannaDevelop** [comment]
🇲🇽

**Comment by edwinb-ai** [comment]
> mexico

¿Cómo pones esa de México? A mí no me sale.

**Comment by gmagannaDevelop** [comment]
Yo lo hice con WhatsApp pero parece que ya está disponible acá también. 
:mexico:

**Comment by gmagannaDevelop** [comment]
entre los dos puntos ponle mexico ;)

**Comment by edwinb-ai** [comment]
:mexico: tsssssssss perro @gmagannaDevelop

**Comment by gmagannaDevelop** [comment]
Excelente, para que ya la pongas en tu readme :100:
